-- ============================================================
-- ETW HTTP 요청 로그 테이블 (PostgreSQL)
-- ============================================================
-- MSSQL 원본 스키마를 PostgreSQL에 맞게 변환한 DDL.
-- NVARCHAR → VARCHAR, DATETIME → TIMESTAMP, IDENTITY → GENERATED ALWAYS AS IDENTITY
-- CREATED_AT 기본값: CURRENT_TIMESTAMP (UTC는 앱 레벨에서 보장)

CREATE TABLE IF NOT EXISTS REQUEST_LOGS (
    REQUEST_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SERVER_ID          INT           NOT NULL,
    EVENT_TIMESTAMP    TIMESTAMP     NOT NULL,
    HTTP_METHOD        VARCHAR(16),
    URL                VARCHAR(2000),
    STATUS_CODE        SMALLINT,
    CLIENT_IP          VARCHAR(45),
    REQUEST_START_TIME TIMESTAMP,
    RESPONSE_END_TIME  TIMESTAMP,
    DURATION_MS        DECIMAL(9, 3),
    BYTES_SENT         BIGINT,
    BYTES_RECEIVED     BIGINT,
    USER_AGENT         VARCHAR(1000),
    REFERER            VARCHAR(2000),
    PROTOCOL_VERSION   VARCHAR(16),
    REQUEST_HEADER     TEXT,
    RESPONSE_HEADER    TEXT,
    CREATED_AT         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스: 조회 패턴에 따라 선택적으로 활성화
CREATE INDEX IF NOT EXISTS IDX_RL_EVENT_TIMESTAMP ON REQUEST_LOGS (EVENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS IDX_RL_SERVER_ID       ON REQUEST_LOGS (SERVER_ID);
CREATE INDEX IF NOT EXISTS IDX_RL_STATUS_CODE     ON REQUEST_LOGS (STATUS_CODE);
CREATE INDEX IF NOT EXISTS IDX_RL_CREATED_AT      ON REQUEST_LOGS (CREATED_AT);

COMMENT ON TABLE  REQUEST_LOGS IS 'ETW HTTP 요청 이벤트 로그';
COMMENT ON COLUMN REQUEST_LOGS.REQUEST_ID         IS '기본키 (자동증가)';
COMMENT ON COLUMN REQUEST_LOGS.SERVER_ID          IS '[SERVER_LIST] 테이블 FK 참조';
COMMENT ON COLUMN REQUEST_LOGS.EVENT_TIMESTAMP    IS 'ETW 이벤트 발생 시각 (UTC)';
COMMENT ON COLUMN REQUEST_LOGS.DURATION_MS        IS '처리 시간 (밀리초)';
COMMENT ON COLUMN REQUEST_LOGS.CREATED_AT         IS 'DB 적재 시각 (UTC)';
